"""Generate shots/ch01.json ... ch06.json.

Every time is written as a beat reference ("bar:K" = start of bar K, fractional K = beats/4, optional +/-seconds)
so the engine resolves it against analysis/beats.json (and snaps it to the 30fps frame grid).
Bar 0 starts at the first downbeat (1.108 s). Geometry helpers mirror the engine's layout so the cursor
lands exactly on buttons, icons and title bars.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
BEATS = json.loads((ROOT / "analysis" / "beats.json").read_text(encoding="utf-8"))
P = BEATS["period"]
BAR0 = BEATS["bar_starts"][0]
END = 40.774
F = 1 / 30  # one frame

def bar(k, off=0.0):
    s = f"bar:{round(k, 4)}"
    if off:
        s += f"{off:+.3f}"
    return s

def sec(k, off=0.0):
    return BAR0 + k * 4 * P + off

# ---------------------------------------------------------------- engine geometry (logical 960x540)
TB = 26
def client(x, y, w, h):
    return x + 4, y + TB + 1, w - 8, h - TB - 5

def dialog_button(win, i, corner=False):
    """Screen position of button i in a dialog (labels all measure 78px), honouring the dialog's scale.
    corner=True gives a point near the button's lower-right so the arrow does not cover the label."""
    cx, cy, cw, ch = client(win["x"], win["y"], win["w"], win["h"])
    n = len(win.get("buttonsList", ["确定"]))
    total = 78 * n + 8 * (n - 1)
    bx = cx + (cw - total) / 2 + i * 86
    by = cy + ch - 12 - 25
    px, py = (bx + 66, by + 20) if corner else (bx + 39, by + 12.5)
    s = win.get("scale", 1)
    mx, my = win["x"] + win["w"] / 2, win["y"] + win["h"] / 2
    return round(mx + (px - mx) * s, 1), round(my + (py - my) * s, 1)

def to_local_delta(win, screen_from, screen_to):
    s = win.get("scale", 1)
    return round((screen_to[0] - screen_from[0]) / s, 1), round((screen_to[1] - screen_from[1]) / s, 1)

def title_grip(x, y, dx=150):
    return x + dx, y + 13

ICON_X = 878
ICON_POS = {"pc": (ICON_X, 12), "bin": (ICON_X, 82), "drum": (ICON_X, 152), "mp3": (ICON_X, 222)}
def icon_center(iid):
    x, y = ICON_POS[iid]
    return x + 34, y + 16

START_BTN = (50, 525)
START_MENU_SHUTDOWN = (314, 487)

class Cursor:
    def __init__(self):
        self.keys, self.clicks, self.hide = [], [], []
    def at(self, t, x, y, ease="inOut"):
        self.keys.append({"t": t, "x": round(x, 1), "y": round(y, 1), "ease": ease})
        return self
    def click(self, t):
        # the pointer must still be on the target when the button goes down: hold the last position until the click
        last = self.keys[-1]
        self.keys.append({"t": t, "x": last["x"], "y": last["y"], "ease": "linear"})
        self.clicks.append(t)
        return self
    def wiggle(self, k0, x, y, amp, n, step=0.0625):
        """quick left-right shakes starting at bar k0, one swing per `step` bars"""
        for i in range(n):
            self.at(bar(k0 + i * step), x + (amp if i % 2 == 0 else -amp), y, "out")
        return self.at(bar(k0 + n * step), x, y, "out")
    def dump(self):
        return {"keys": self.keys, "clicks": self.clicks, "hide": self.hide}

def err(id_, t0, t1, x, y, text, glyph="error", buttons=("确定",), w=330, h=130, z=10, **kw):
    d = {"id": id_, "type": "error", "t0": t0, "t1": t1, "x": x, "y": y, "w": w, "h": h, "z": z,
         "title": kw.pop("title", "APT."), "text": text, "glyph": glyph, "buttonsList": list(buttons)}
    d.update(kw)
    return d

def write(name, data):
    data["_note"] = "generated by shots/build.py - edit the generator, not this file"
    (HERE / name).write_text(json.dumps(data, ensure_ascii=False, indent=1), encoding="utf-8")

# the singer + bass drum cut-out: the drum strip (minus its stand) drops 47px so both sit on the taskbar
SIT = {"x": 0, "y": 130, "h": 380, "layer": "back", "pop": False,
       "parts": [{"x0": 0, "x1": 545}, {"x0": 560, "x1": 1148, "dy": 47, "bounce": 0.06}]}
SIT_GROUND = [{"x": 140, "y": 510, "w": 320, "h": 18, "a": 0.55}, {"x": 410, "y": 510, "w": 260, "h": 16, "a": 0.5}]

# ================================================================= ch01  boot + welcome   (0 - bar 1)
# welcome user tiles are drawn at 1.25x around (500,196)
U1_NAME, U2_TILE = (612, 236), (540, 352)
c = Cursor()
c.at(bar(0), *U1_NAME)
c.wiggle(0.0, U1_NAME[0], U1_NAME[1], 6, 4, step=0.0625)            # hesitating over APT 1号
c.at(bar(0.25, -0.1), *U1_NAME).at(bar(0.25), *U2_TILE, "out")       # jump to APT 2号 on beat 2
c.at(bar(0.5, -0.05), *U2_TILE).click(bar(0.5)).at(bar(0.625), 520, 440, "out")   # click on beat 3, then get out of the way
write("ch01.json", {
    "chapter": 1, "range": [0, bar(1)],
    "base": [
        {"t0": 0, "t1": bar(0), "type": "boot"},
        {"t0": bar(0), "t1": bar(1), "type": "welcome", "userScale": 1.25, "users": [
            {"name": "APT 1号", "clip": "heads_b", "frame": 289, "hover": [[bar(0), bar(0.25)]]},
            {"name": "APT 2号", "clip": "heads_b", "frame": 319, "hover": [[bar(0.25), bar(1)]], "selectAt": bar(0.5)},
        ]},
    ],
    "cursor": c.dump(),
})

# ================================================================= ch02  desktop + main gag + screensaver   (bar 1 - bar 4)
c = Cursor()
mp3 = icon_center("mp3")
e_nf = err("e_notfound", bar(1.5), bar(2), 290, 175, ["找不到 APT。", "用 apt 安装？"], glyph="error",
           buttons=("是(Y)", "否(N)"), title="Pinkdows XP", w=360, h=150, scale=1.2, textSize=17, z=5,
           hover=[{"btn": 0, "t0": bar(1.75), "t1": bar(2)}], press=[{"btn": 0, "t": bar(2, -2 * F)}])
yes = dialog_button(e_nf, 0, corner=True)
c.at(bar(1), 520, 440).at(bar(1.25, -0.14), *mp3).click(bar(1.25, -0.1)).click(bar(1.25))
c.at(bar(1.5), *mp3).at(bar(1.75, -0.05), *yes).click(bar(2, -2 * F))
TERM = (30, 262, 480, 150)
MEDIA = (350, 40, 500, 380)
term = {"id": "term", "type": "terminal", "t0": bar(2), "t1": bar(3.25), "z": 2,
        "x": TERM[0], "y": TERM[1], "w": TERM[2], "h": TERM[3], "fontSize": 19,
        "title": "命令提示符 - apt", "icon": "terminal",
        "lines": [
            {"prompt": "C:\\> ", "dimAt": bar(2.5),
             "chunks": [{"t": bar(2), "s": ""}, {"t": bar(2.125), "s": "sudo "}, {"t": bar(2.25), "s": "apt "},
                        {"t": bar(2.375), "s": "install "}, {"t": bar(2.5, -0.1), "s": "apt"}]},
            {"t": bar(2.5), "s": "将同时安装：鼓 嘴唇 皮衣", "color": "#7CFC00", "flash": True},
            {"chunks": [{"t": bar(2.5), "s": "[Y/n] "}, {"t": bar(2.625), "s": "Y"}]},
        ]}
media = {"id": "media", "type": "media", "t0": bar(2.75), "t1": bar(7.25), "z": 3,
         "x": MEDIA[0], "y": MEDIA[1], "w": MEDIA[2], "h": MEDIA[3],
         "title": "APT.mp3 - Pinkdows Media Player", "taskTitle": "Pinkdows Media Player", "icon": "media",
         "srcOffset": -0.27, "minimized": [[bar(4), bar(7.25)]]}
c.at(bar(2.25), 300, 470).at(bar(2.75, -0.1), 250, 470).at(bar(3.25), 252, 470)
c.hide.append([bar(3.25), bar(3.75)])
c.at(bar(3.75), 480, 120)
c.wiggle(3.75, 480, 120, 40, 4, step=0.0625)                          # shake over the upper lip: screensaver wakes
write("ch02.json", {
    "chapter": 2, "range": [bar(1), bar(4)],
    "base": [
        {"t0": bar(1), "t1": bar(3.25), "type": "desktop"},
        {"t0": bar(3.25), "t1": bar(4), "type": "screensaver",
         "srcKeys": [{"t": bar(3.25), "ts": 6.13}, {"t": bar(4), "ts": 7.30, "ease": "linear"}]},
    ],
    "icons": [{"id": "mp3", "label": "APT.mp3", "icon": "mp3", "x": ICON_POS["mp3"][0], "y": ICON_POS["mp3"][1],
               "selectedFrom": bar(1.25, -0.1), "selectedTo": bar(2)}],
    "windows": [e_nf, term, media],
    "cursor": c.dump(),
})

# ================================================================= ch03  sticker bombing + logoff   (bar 4 - bar 8)
# 5x3 grid of sticker slots (bottom-right left free for the tray balloons, right column for icons)
import random
rng = random.Random(1149)
# director's call after round 3: slapped on messily - mixed sizes, tilted, jittered, overlaps allowed
slots = [(110, 105), (290, 90), (470, 120), (640, 95), (790, 140), (190, 255), (380, 240), (560, 270), (720, 270),
         (90, 400), (260, 395), (450, 400), (600, 420), (160, 175), (520, 340), (330, 330)]
order = [0, 6, 3, 9, 1, 12, 7, 4, 10, 13, 2, 15, 5, 11, 8, 14]
# one per beat until 9.97 s, then one per half beat up to the big squeeze on 11.98 s
times = [4, 4.25, 4.5, 4.75, 5, 5.25, 5.5] + [5.5 + 0.125 * i for i in range(1, 10)]
# distinct, sharp frames, alternating singers (heads_b 271-305 = APT 1号, the rest = APT 2号)
frames = [("heads_a", 232), ("heads_b", 298), ("heads_b", 319), ("heads_a", 247), ("heads_b", 289), ("heads_b", 328),
          ("heads_b", 304), ("heads_a", 223), ("heads_b", 343), ("heads_b", 292), ("heads_b", 307), ("heads_b", 274),
          ("heads_b", 352), ("heads_a", 238), ("heads_b", 280), ("heads_b", 337)]
stickers = []
for i in range(16):
    x, y = slots[order[i]]
    clip, fr = frames[i]
    stickers.append({"t0": bar(times[i]), "t1": bar(7), "clip": clip, "frame": fr, "bbox": True,
                     "x": x + rng.randint(-25, 25), "y": y + rng.randint(-20, 20), "h": round(118 * rng.uniform(0.85, 1.3)),
                     "rot": rng.uniform(-13, 13), "stroke": 3, "bounce": 0.08,
                     "pulseAt": bar(6.75), "pulseAmp": 0.13, "shadow": True, "layer": "back"})
drag = stickers[1]                                                     # slapped on at bar 4.25
DX, DY = 170, 120
drag["lift"] = [bar(5), bar(5.5)]
drag["keys"] = [{"t": bar(5), "x": drag["x"], "y": drag["y"]}, {"t": bar(5.375), "x": drag["x"] + DX, "y": drag["y"] + DY},
                {"t": bar(5.5), "x": drag["x"], "y": drag["y"], "ease": "back"}]
icons3 = []
for iid, k, label in [("pc", 5.0, "apt.exe"), ("bin", 5.5, "复件 apt.exe"), ("drum", 6.0, "复件 (2) apt.exe"), ("mp3", 6.5, "复件 (3) apt.exe")]:
    x, y = ICON_POS[iid]
    icons3.append({"id": iid, "label": label, "icon": "apt", "x": x, "y": y, "t0": bar(k), "morph": True,
                   "selectedFrom": bar(k - 0.25), "selectedTo": bar(k)})
logoff_dlg = err("logoff_fail", bar(7.5), bar(8), 330, 200, "注销失败：APT. 不让走", glyph="error", buttons=("好吧",),
                 w=340, h=130, title="Pinkdows XP", scale=1.2, textSize=16, z=50, taskbar=False,
                 hover=[{"btn": 0, "t0": bar(7.625), "t1": bar(8)}], press=[{"btn": 0, "t": bar(8, -2 * F)}])
ok = dialog_button(logoff_dlg, 0, corner=True)
c = Cursor()
c.at(bar(4), 492, 300).at(bar(5, -0.1), drag["x"], drag["y"]).click(bar(5)).at(bar(5.375), drag["x"] + DX, drag["y"] + DY)
c.at(bar(5.75), 600, 480).at(bar(7), 610, 480)   # rest left of the tray balloon, never on its text
c.hide.append([bar(7), bar(7.5)])
c.at(bar(7.5), ok[0] + 50, ok[1] + 50).at(bar(7.625), *ok).click(bar(8, -2 * F))
write("ch03.json", {
    "chapter": 3, "range": [bar(4), bar(8)],
    "base": [
        {"t0": bar(4), "t1": bar(7), "type": "desktop"},
        {"t0": bar(7), "t1": bar(7.25), "type": "video"},
        {"t0": bar(7.25), "t1": bar(8), "type": "logoff", "video": True, "srcOffset": 0.05, "dim": 0.6, "showWindows": True,
         "msgKeys": [{"t": bar(7.25), "s": "正在注销..."}, {"t": bar(7.5), "s": ""}]},
    ],
    "stickers": stickers,
    "icons": icons3,
    "windows": [logoff_dlg],
    "balloons": [
        {"t0": bar(4.5), "t1": bar(5.5), "title": "发现新硬件", "text": "APT.", "icon": "hardware", "textSize": 18, "bold": True, "scale": 1.15},
        {"t0": bar(5.5), "t1": bar(6.75), "title": "APT. 驱动已安装", "text": "注销后生效", "icon": "hardware", "textSize": 16, "bold": True, "scale": 1.15},
    ],
    "cursor": c.dump(),
})

# ================================================================= ch04  sitting on the taskbar + notepad + task manager   (bar 8 - bar 15.25)
AX, AY, AS = 760, 360, 1.4                     # drumstick assistant position / scale
assist_btn = (AX - 16 * AS, AY - 34 * AS)       # its "好的" button (independent of bubble width)
NOTE_W, NOTE_H = 420, 338                       # video area 392x283 = 1.386, the bordered lyric shots' own ratio
P0, P1, P2, P3 = (270, 50), (20, 40), (100, 150), (10, 60)
note = {"id": "notepad", "type": "notepad", "t0": bar(9.5), "t1": bar(15.25), "x": P0[0], "y": P0[1], "w": NOTE_W, "h": NOTE_H,
        "title": "蹦迪教程.txt - 记事本", "taskTitle": "蹦迪教程.txt", "icon": "notepad",
        "zKeys": [{"t": bar(9.5), "z": 4}, {"t": bar(11.75, -0.1), "z": 6}, {"t": bar(13.75, -0.1), "z": 8}],
        "moves": [{"t": bar(10.25), "x": P0[0], "y": P0[1]}, {"t": bar(10.5), "x": P1[0], "y": P1[1], "ease": "back"},
                  {"t": bar(11.75), "x": P1[0], "y": P1[1]}, {"t": bar(12), "x": P2[0], "y": P2[1], "ease": "back"},
                  {"t": bar(13.75), "x": P2[0], "y": P2[1]}, {"t": bar(14), "x": P3[0], "y": P3[1], "ease": "back"}]}
TM = (530, 30, 330, 450)
tm = {"id": "taskmgr", "type": "taskmgr", "t0": bar(10.5), "t1": bar(15.25), "x": TM[0], "y": TM[1], "w": TM[2], "h": TM[3],
      "title": "Pinkdows 任务管理器", "icon": "taskmgr", "zKeys": [{"t": bar(10.5), "z": 5}, {"t": bar(12.5, -0.1), "z": 7}],
      "cpuRamp": [bar(10.5), bar(15)], "cpuFull": bar(15), "shake": [bar(15)],
      "press": [{"t": bar(12.75, -2 * F)}], "procs": []}
for name, cpu, mem in [("System", 0, "240 K"), ("explorer.exe", 1, "18,204 K"), ("notepad.exe", 0, "2,912 K"), ("taskmgr.exe", 2, "4,416 K")]:
    tm["procs"].append({"t": bar(10.5), "name": name, "cpu": cpu, "mem": mem, "user": "SYSTEM"})
mems = iter(f"{140 + (i * 7) % 10},{(i * 379) % 900 + 100} K" for i in range(100))
k = 10.75
while k <= 14.75 + 1e-9:
    row = {"t": bar(k), "name": "apt.exe", "cpu": "ramp", "mem": next(mems)}
    if abs(k - 12.5) < 1e-9:
        row.update({"selFrom": bar(12.5), "killFrom": bar(12.75), "until": bar(13)})   # select, flash red, gone on the downbeat
    tm["procs"].append(row)
    k += 0.25
tm["procs"] += [{"t": bar(13), "name": "apt.exe", "cpu": "ramp", "mem": "149,149 K", "hl": 0.4},
                {"t": bar(13, F), "name": "apt.exe", "cpu": "ramp", "mem": "149,150 K", "hl": 0.4}]
refuse = err("refuse", bar(13.25), bar(13.75), 545, 210, "apt.exe 拒绝被结束", glyph="error", buttons=("好吧",),
             w=300, title="Pinkdows 任务管理器", scale=1.1, textSize=16, z=20, taskbar=False)
tcx, tcy, tcw, tch = client(*TM)
end_btn = (tcx + tcw - 98 + 50, tcy + tch - 23 + 14)
rows_at_sel = 4 + int(round((12.5 - 10.75) / 0.25)) + 1
sel_row = (tcx + 60, tcy + 42 + 20 + (rows_at_sel - 1) * 16 + 8)
c = Cursor()
c.at(bar(8), 700, 470).at(bar(8.5), 600, 470).at(bar(9.25, -0.08), *assist_btn).click(bar(9.5, -0.05))
c.at(bar(10.25, -0.1), *title_grip(*P0)).click(bar(10.25, -0.1)).at(bar(10.5), *title_grip(*P1), "back")
c.at(bar(11.75, -0.1), *title_grip(*P1)).click(bar(11.75, -0.1)).at(bar(12), *title_grip(*P2), "back")
c.at(bar(12.5, -0.06), *sel_row).click(bar(12.5)).at(bar(12.75, -0.08), *end_btn).click(bar(12.75, -2 * F))
c.at(bar(13.75, -0.1), *title_grip(*P2)).click(bar(13.75, -0.1)).at(bar(14), *title_grip(*P3), "back").at(bar(15), 480, 476)
write("ch04.json", {
    "chapter": 4, "range": [bar(8), bar(15.25)],
    "base": [{"t0": bar(8), "t1": bar(15.25), "type": "desktop"}],
    "mattes": [dict(SIT, t0=bar(8), t1=bar(9.5), clip="sit", first=425, last=495)],
    "ground": [dict(g, t0=bar(8), t1=bar(9.5)) for g in SIT_GROUND],
    "clock": [{"t0": bar(8), "t1": bar(9.5), "blink": True}],
    "overlays": [{"type": "assistant", "t0": bar(8.5), "t1": bar(9.5), "x": AX, "y": AY, "scale": AS, "sayAt": bar(8.5),
                  "say": "你似乎在蹦迪，需要帮助吗？", "button": "好的", "hoverAt": bar(9.25), "press": bar(9.5, -0.05)}],
    "windows": [note, tm, refuse],
    "cursor": c.dump(),
})

# ================================================================= ch05  error barrage + video call   (bar 15.25 - bar 23)
G = {"group": "APT."}
d1 = err("d1", bar(15.5), None, 500, 50, "APT. 已在运行", "error", z=11, **G)
d2 = err("d2", bar(15.75), None, 320, 6, "APT. 没有响应", "warn", z=12, **G)
d3 = err("d3", bar(16.0), bar(16.25), 330, 150, "APT. 遇到问题需要关闭", "error", z=13, press=[{"btn": 0, "t": bar(16.25, -2 * F)}], **G)
copies = [err(f"c{i}", bar(16.25 + 0.125 * i), None, 560 + 14 * i, 290 + 14 * i, "APT. 正在复制自己", "warn", z=14 + i, **G) for i in range(3)]
d4 = err("d4", bar(16.75), None, 620, 60, "内存不足：全是 APT.", "warn", z=18, **G)
dq = err("dq", bar(17), bar(18), 520, 150, "是否结束 APT.？", "question", buttons=("结束", "继续蹦迪"), w=340, z=30, scale=1.25,
         textSize=16, hover=[{"btn": 1, "t0": bar(17.5), "t1": bar(18)}], press=[{"btn": 1, "t": bar(18, -2 * F)}], **G)
barrage = [d1, d2, copies[0], copies[1], copies[2], d4]
for i, d in enumerate(barrage):                    # everything left vanishes in a chain, one per frame, from the bar-18 downbeat
    d["t1"] = bar(18, (i + 1) * F)
    d["shake"] = [bar(16.5), bar(17)]
c = Cursor()
c.at(bar(15.25), 480, 476).at(bar(16.25, -0.08), *dialog_button(d3, 0, corner=True)).click(bar(16.25, -2 * F))
c.at(bar(16.75), 470, 480).at(bar(17.5, -0.05), *dialog_button(dq, 1, corner=True)).click(bar(18, -2 * F))
call = err("call", bar(18.25), bar(19), 330, 170, "APT 2号 邀你蹦迪", glyph="camera", buttons=("接受", "拒绝"),
           w=320, h=140, title="视频通话", z=40, scale=1.5, textSize=17, press=[{"btn": 0, "t": bar(19, -2 * F)}])
rej0 = dialog_button(call, 1)
EXTRA = (640, 78)                                  # where the runaway 拒绝 button ends up living in the taskbar
jump1, jump2 = (850, 110), (EXTRA[0] + EXTRA[1] / 2, 534)   # 534: the 1.5x button sinks fully below the taskbar edge
d1x, d1y = to_local_delta(call, rej0, jump1)
d2x, d2y = to_local_delta(call, rej0, jump2)
call["dodge"] = [{"btn": 1, "keys": [{"t": 0, "dx": 0, "dy": 0}, {"t": bar(18.5, -F), "dx": 0, "dy": 0},
                                     {"t": bar(18.5, 2 * F), "dx": d1x, "dy": d1y, "ease": "out"},
                                     {"t": bar(18.75, -F), "dx": d1x, "dy": d1y},
                                     {"t": bar(18.75, 2 * F), "dx": d2x, "dy": d2y, "ease": "out"}]}]
acc = dialog_button(call, 0, corner=True)
c.at(bar(18.5, -0.04), *rej0).at(bar(18.75, -0.04), *jump1).at(bar(19, -0.1), *acc).click(bar(19, -2 * F))
vc = {"id": "videocall", "type": "videocall", "t0": bar(19), "t1": bar(23), "x": 190, "y": 46, "w": 580, "h": 430,
      "title": "视频通话 - APT 1号, APT 2号", "taskTitle": "视频通话", "icon": "camera", "timerFrom": bar(19), "z": 50,
      "names": ["APT 1号", "APT 2号"], "shake": [bar(19), bar(19.5)], "fit": "contain",
      "pulse": [bar(19 + 0.5 * i) for i in range(2, 8)],
      "notes": [{"t": bar(21), "t1": bar(21.75), "s": "画质已降为 APT."}, {"t": bar(22), "t1": bar(22.75), "s": "APT 2号 正在输入…"}],
      # the call footage stops on its last frame before the lips shot (37.83 s) instead of leaking it
      "srcKeys": [{"t": sec(19), "ts": sec(19)}, {"t": 37.80, "ts": 37.80, "ease": "linear"}, {"t": 38.3, "ts": 37.80}],
      "moves": [{"t": bar(20), "x": 190, "y": 46, "w": 580, "h": 430},
                {"t": bar(20, 0.1), "x": 0, "y": 0, "w": 960, "h": 510, "ease": "out"}]}
c.at(bar(20, -0.18), 480, 59).click(bar(20, -0.12)).click(bar(20)).at(bar(20.5), 700, 200)
KNEEL = {"clip": "kneel", "first": 801, "last": 893, "groundY": 510, "pop": False,
         "keys": [{"t": 26.605, "x": -20, "h": 560}, {"t": sec(17), "x": -20, "h": 560},
                  {"t": sec(17, 2 * F), "x": -60, "h": 760, "ease": "out"}]}
write("ch05.json", {
    "chapter": 5, "range": [bar(15.25), bar(23)],
    "base": [{"t0": bar(15.25), "t1": bar(23), "type": "desktop"}],
    "mattes": [
        dict(SIT, t0=bar(15.25), t1=26.605, clip="sit2", first=769, last=797),
        dict(KNEEL, t0=26.605, t1=bar(17), x=-20, y=0, h=560, layer="back"),
        dict(KNEEL, t0=bar(17), t1=29.827, x=-20, y=0, h=560, layer="front"),
    ],
    "ground": [dict(g, t0=bar(15.25), t1=26.605) for g in SIT_GROUND] +
              [{"t0": 26.605, "t1": 29.827, "x": 260, "y": 510, "w": 300, "h": 18, "a": 0.5}],
    "windows": [d1, d2, d3] + copies + [d4, dq, call, vc],
    "taskExtras": [{"t0": bar(18.75, 2 * F), "t1": bar(24.25), "label": "拒绝", "x": EXTRA[0], "w": EXTRA[1]}],
    "balloons": [{"t0": bar(21.5), "t1": bar(22.25), "title": "网络连接", "text": "带宽已被 APT. 占满", "icon": "hardware", "textSize": 16, "bold": True, "scale": 1.15}],
    "cursor": c.dump(),
})

# ================================================================= ch06  screensaver + dancers + shutdown   (bar 23 - end)
# director's call after round 3: lips end on bar 23.75 so the two dancers get one beat alone before the start menu
c = Cursor()
c.hide.append([bar(23), bar(23.5)])
c.at(bar(23.5), 480, 150)
c.wiggle(23.5, 480, 150, 110, 2, step=0.125)                        # two big swings wake the screensaver
c.at(bar(23.75, 0.1), 240, 470).at(bar(24, -0.05), *START_BTN).click(bar(24))
SHUT_ICON = (286, 487)                                               # click the power icon, not the label
c.at(bar(24.25, -0.1), *SHUT_ICON).click(bar(24.25, -F))
DANCE_H = 360
write("ch06.json", {
    "chapter": 6, "range": [bar(23), END],
    "base": [
        {"t0": bar(23), "t1": bar(23.75), "type": "screensaver",
         "srcKeys": [{"t": bar(23), "ts": 37.86}, {"t": bar(23.75), "ts": 39.40, "ease": "linear"}]},
        {"t0": bar(23.75), "t1": bar(24.25), "type": "desktop"},
        {"t0": bar(24.25), "t1": END + 1, "type": "shutdown", "ubuntu": bar(24.375)},
    ],
    "mattes": [{"t0": bar(23.75), "t1": bar(24.25), "clip": "dance", "first": 1185, "last": 1221, "skip": [1194, 1198],
                "x": 326, "y": 0, "h": DANCE_H, "groundY": 510, "sink": 2, "layer": "back", "pop": False,
                "bounce": 0.03, "ax": 0.5, "ay": 1}],
    "ground": [{"t0": bar(23.75), "t1": bar(24.25), "x": 475, "y": 510, "w": 150, "h": 14, "a": 0.55},
               {"t0": bar(23.75), "t1": bar(24.25), "x": 739, "y": 510, "w": 130, "h": 14, "a": 0.55}],
    "startmenu": [{"t0": bar(24), "t1": bar(24.25), "user": "APT 2号", "avatar": {"clip": "heads_b", "frame": 319},
                   "hoverOff": bar(24.25, -0.1), "pressOff": bar(24.25, -2 * F),
                   "left": [{"icon": "apt", "label": "apt", "sub": "安装 APT."}] + [{"icon": "apt", "label": "apt"}] * 5}],
    "cursor": c.dump(),
})
print("wrote ch01..ch06")
